const dataSource = [
    "Nhược thị là vấn đề của Não bộ chứ không phải chỉ riêng mắt",
    "Lác Lé, Nhược thị hoàn toàn có thể hết được nhờ huấn luyện.",
    "Nhược thị hoàn toàn có thể cải thiện nhờ phương pháp huấn luyện thị giác đúng cách.",
    "Luyện tập mắt mỗi ngày giúp tăng cường sự kết nối giữa não bộ và thị giác.",
    "Phương pháp huấn luyện thị giác không xâm lấn mang lại hiệu quả bền vững cho đôi mắt.",
    "Cải thiện thị lực hai mắt là chìa khóa để có một tầm nhìn sâu và chuẩn xác.",
    "Nhược thị không phải là bệnh lý vĩnh viễn nếu được can thiệp bằng bài tập phù hợp.",
    "Kiên trì luyện tập giúp khôi phục chức năng thị giác cho người bị lác và nhược thị.",
    "Tầm nhìn rõ nét giúp bạn tự tin hơn trong công việc và các hoạt động đời sống.",
    "Huấn luyện thị giác giúp đôi mắt phối hợp nhịp nhàng và giảm căng thẳng khi làm việc.",
    "Hãy dành thời gian mỗi ngày để chăm sóc và rèn luyện sức khỏe cho đôi mắt bạn.",
    "Đôi mắt sáng khỏe là nền tảng quan trọng cho mọi hoạt động học tập và lao động.",
    "Phương pháp tập luyện mới giúp phục hồi thị lực mà không cần can thiệp phẫu thuật.",
    "Nhược thị có thể hết được thông qua lộ trình huấn luyện chuyên biệt và bài bản.",
    "Tăng cường khả năng tập trung của mắt bằng các bài tập vận động nhãn cầu nhẹ nhàng.",
    "Tầm nhìn của bạn sẽ thay đổi tích cực khi hệ thống thị giác được kích hoạt đúng.",
    "Phục hồi chức năng thị giác giúp trẻ em có tương lai học tập tươi sáng và thuận lợi.",
    "Sự phối hợp giữa hai mắt là yếu tố quyết định để có thị lực hoàn hảo nhất.",
    "Luyện tập thị lực là quá trình kiên trì để đạt được kết quả phục hồi tốt nhất.",
    "Hãy để đôi mắt được thư giãn và rèn luyện đúng cách sau mỗi giờ làm việc căng thẳng.",
    "Khả năng hợp nhất hình ảnh giữa hai mắt là mục tiêu quan trọng trong huấn luyện thị giác.",
    "Luyện tập điều tiết giúp mắt thích nghi tốt hơn với các khoảng cách nhìn khác nhau.",
    "Xóa bỏ hiện tượng ức chế thị giác giúp mắt nhược thị dần phục hồi chức năng nhìn rõ.",
    "Các bài tập phối hợp tay mắt giúp não bộ xử lý thông tin hình ảnh nhanh nhạy hơn.",
    "Chứng lác mắt có thể được cải thiện đáng kể thông qua việc cân bằng cơ nhãn cầu.",
    "Huấn luyện thị giác không chỉ dành cho trẻ em mà còn hiệu quả với cả người trưởng thành.",
    "Mỗi bài tập là một bước tiến gần hơn đến việc sở hữu thị lực hai mắt hoàn hảo.",
    "Sử dụng công nghệ và dụng cụ chuyên dụng giúp tối ưu hóa quá trình phục hồi thị lực.",
    "Nhược thị sâu vẫn có cơ hội cải thiện nếu áp dụng đúng lộ trình kích thích thị giác.",
    "Cải thiện độ nhạy tương phản giúp đôi mắt nhìn rõ hơn trong các điều kiện ánh sáng yếu.",
    "Tầm nhìn 3D và khả năng ước lượng khoảng cách phụ thuộc vào sự khỏe mạnh của đôi mắt.",
    "Đừng để nhược thị cản trở ước mơ nghề nghiệp và những đam mê của bản thân bạn.",
    "Huấn luyện thị giác giúp giảm tình trạng mỏi mắt và đau đầu khi làm việc máy tính.",
    "Sự kiên trì trong từng bài tập nhỏ sẽ mang lại sự thay đổi lớn cho tầm nhìn.",
    "Cân bằng thị lực giữa hai mắt giúp loại bỏ hiện tượng hình to hình bé khó chịu.",
    "Phương pháp khoa học giúp đôi mắt hoạt động bền bỉ mà không cần dùng đến thuốc.",
    "Hãy để chuyên gia tư vấn lộ trình tập luyện phù hợp nhất với tình trạng mắt bạn.",
    "Kích thích võng mạc đúng cách là chìa khóa để đánh thức thị giác đang bị ngủ quên.",
    "Đôi mắt khỏe mạnh giúp bạn tận hưởng trọn vẹn vẻ đẹp của cuộc sống xung quanh."
];